# Generated by Django 2.2.7 on 2020-02-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeju2020', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jeju2020.Candidate')),
                ('upload', models.FileField(blank=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jeju2020.Candidate')),
                ('text1', models.TextField(blank=True)),
                ('text2', models.TextField(blank=True)),
                ('text3', models.TextField(blank=True)),
                ('text4', models.TextField(blank=True)),
                ('text5', models.TextField(blank=True)),
                ('more_info', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
