# Generated by Django 2.2.7 on 2020-02-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeju2020', '0002_auto_20200203_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='number',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('JHD', '자유한국당'), ('TMJ', '더민주'), ('JED', '정의당')], default='무소속', max_length=10),
        ),
        migrations.AlterField(
            model_name='press',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jeju2020.Candidate'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jeju2020.Candidate'),
        ),
    ]
