# Generated by Django 2.2.7 on 2020-02-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeju2020', '0003_auto_20200203_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='party',
        ),
        migrations.AddField(
            model_name='candidate',
            name='region',
            field=models.CharField(choices=[('gab', '제주갑'), ('eul', '제주을'), ('byeong', '제주병')], default='무소속', max_length=10),
        ),
        migrations.AlterField(
            model_name='press',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jeju2020.Candidate'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jeju2020.Candidate'),
        ),
    ]
