# Generated by Django 2.2.7 on 2020-02-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeju2020', '0005_auto_20200203_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='upload',
        ),
        migrations.AddField(
            model_name='press',
            name='company',
            field=models.CharField(default='에디터', max_length=20),
        ),
        migrations.AddField(
            model_name='press',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='후보', max_length=100),
        ),
        migrations.AlterField(
            model_name='press',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jeju2020.Candidate'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jeju2020.Candidate'),
        ),
    ]
