# Generated by Django 2.2.7 on 2020-02-05 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jeju2020', '0006_auto_20200205_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='press',
            name='company',
        ),
        migrations.AddField(
            model_name='press',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 12, 43, 50, 556989, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='press',
            name='where',
            field=models.CharField(default='에디터', max_length=20),
        ),
        migrations.AlterField(
            model_name='press',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jeju2020.Candidate'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jeju2020.Candidate'),
        ),
    ]
