# Generated by Django 2.2.7 on 2020-02-05 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jeju2020', '0014_auto_20200205_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 5, 13, 43, 7, 994213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='press',
            name='candidate',
            field=models.ForeignKey(default='hi', on_delete=django.db.models.deletion.CASCADE, to='jeju2020.Candidate'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jeju2020.Candidate'),
        ),
    ]
