# Generated by Django 2.2.7 on 2020-02-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeju2020', '0025_auto_20200210_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRpromist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=100)),
                ('brief', models.TextField(blank=True)),
                ('text1', models.TextField(blank=True)),
                ('text2', models.TextField(blank=True)),
                ('text3', models.TextField(blank=True)),
                ('text4', models.TextField(blank=True)),
                ('text5', models.TextField(blank=True)),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='press',
            name='candidate',
            field=models.ForeignKey(default='hi', on_delete=django.db.models.deletion.CASCADE, to='jeju2020.Candidate'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jeju2020.Candidate'),
        ),
    ]
