# Generated by Django 2.2.7 on 2020-02-19 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeju2020', '0026_auto_20200219_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BRpromist',
            new_name='BRpromise',
        ),
        migrations.AlterField(
            model_name='press',
            name='candidate',
            field=models.ForeignKey(default='hi', on_delete=django.db.models.deletion.CASCADE, to='jeju2020.Candidate'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jeju2020.Candidate'),
        ),
    ]
